apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../manifests/node-exporter.yaml
  - ../../manifests/blackbox-exporter.yaml
  - ../../manifests/prometheus.yaml
  - memory-stressor.yaml
configMapGenerator:
  - name: prometheus-rules
    files:
      - alerts.yml
generatorOptions:
  disableNameSuffixHash: true
